#!/bin/sh
# Installed by `just hooks`. Whatever breaks CI has to break here first: a
# thirty-second round trip locally beats a red pull request five minutes
# later.
set -e

gofmt -l . | grep . && { echo "gofmt: the files above are not formatted"; exit 1; }
go vet ./...
go test ./...
